# Site settings
title: Lilly Bernhardt
email: lillyhelena.be@gmx.de
url: https://github.com/LillyHel/lillyhel.github.io
description: "Hi, I am Lilly! Let's design and code some cool projects together."
keywords: "web development, frontend development, iOS Development, UI Design, UX Design"
skills: "Frontend Developer - UI / UX Designer"
meta_author: Bernhardt Lilly

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 0f0f0f #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 86AC92 #FD6E8A
  secondary-dark: 000000 #A2122F

# Footer settings
footer:
  copyright: Lilly Bernhardt
  contact: Contact
  phone: "+49 17657655122"
  social: Around the Web

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Heynahtsstr. 7
  - line: 01309, Dresden

# Credits content

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
